### PR TITLE
MAINT: always attach requirement to NoPackageError

### PR DESCRIPTION
**Pull request by johntyree**
That's all we do here.

### CODE REVIEW

**Comment by cournape** [comment]
Can I ask to swap the argument order ? I think we always want a requirement, but we could use a default message string

**Comment by cournape** [comment]
@johntyree does the comment make sense ? It would be good to get this in master and update jaguar with it

**Comment by johntyree** [comment]
Yes. Just haven't gotten to it. Was doing docs instead. I'll try to wrap up
these PRs with very little work left on them today

**Comment by johntyree** [comment]
What kind of default message? I was thinking the implementation would look something like
```python
class NoPackageFound(SolverException):
    def __init__(self, requirement, *a, **kw):
        super(NoPackageFound, self).__init__(*a, **kw)
        self.requirement = requirement
```
Is that sufficient?

**Comment by johntyree** [comment]
Or possibly:
```python
class NoPackageFound(SolverException):
    def __init__(self, requirement, *a, **kw):
        super(NoPackageFound, self).__init__(*a, **kw)
        self.requirement = requirement
        self.args = self.args or (str(requirement),)
```

**Comment by cournape** [comment]
LGTM

**Pull request merged**
