### PR TITLE
REF: split policy module into subpackage

### PR DESCRIPTION
**Pull request by johntyree**
This is just a refactor.

### CODE REVIEW

**Comment by cournape** [comment]
I think some removal are missing, correct ?

**Comment by johntyree** [comment]
Huh. Yeah I'm not sure what happened there. The old policy module should be removed. I'll look at it today.

**Comment by johntyree** [comment]
@cournape

**Comment by cournape** [comment]
I am assuming the code did not change beyond import fixes, in which case LGTM

**Pull request merged**
