### PR TITLE
Unbundle

### PR DESCRIPTION
**Pull request by cournape**
Update to latest enstaller, don't use submodule anymore.

### CODE REVIEW

**Comment by cournape** [comment]
@johntyree should be ready to merge now

**Comment by johntyree** [comment]
This seems to break tests run via `tox` locally for me. I tried recreating my virtualenv from scratch and deleting `.tox` as well. I don't know how it works on Travis.

```
john@eleanor ~/projects/enthought/sat-solver (unbundle $)
$ tox
GLOB sdist-make: /home/john/projects/enthought/sat-solver/setup.py
py27 create: /home/john/projects/enthought/sat-solver/.tox/py27
py27 installdeps: -rdev_requirements.txt
ERROR: invocation failed (exit code 1), logfile: /home/john/projects/enthought/sat-solver/.tox/py27/log/py27-1.log
ERROR: actionid=py27
msg=getenv
cmdargs=[local('/home/john/projects/enthought/sat-solver/.tox/py27/bin/pip'), 'install', '-rdev_requirements.txt']
env={'XDG_VTNR': '7', 'GIT_PS1_SHOWDIRTYSTATE': '1', 'LC_PAPER': 'en_US.UTF-8', 'LC_ADDRESS': 'en_US.UTF-8', 'XDG_SESSION_ID': 'c1', 'LC_MONETARY': 'en_US.UTF-8', 'SHELL': '/bin/bash', 'TERM': 'screen-256color', 'CLOJURE_HOME': '/usr/share/clojure', 'HISTSIZE': '9999', 'GREP__OPTIONS': '--color=auto', 'HADOOP_PREFIX': '/usr/lib/hadoop', 'WINDOWID': '31457289', 'TRADUISONS_SECRET': '89s96ZsYQAWUCFkzCCXG8OrRg35qUCBezl3ID1omIhw=', 'LC_NUMERIC': 'en_US.UTF-8', 'OLDPWD': '/home/john', 'ANT_HOME': '/usr/share/apache-ant', 'USER': 'john', 'HISTFILESIZE': '50000', 'MPD_HOST': 'raspberrypi', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LC_TELEPHONE': 'en_US.UTF-8', 'SSH_AUTH_SOCK': '/run/user/1000/ssh-agent.socket', 'VIRTUAL_ENV': '/home/john/projects/enthought/sat-solver/.tox/py27', 'TMUX': '/tmp/tmux-1000/default,1239,0', 'MAVEN_OPTS': '-Xmx512m', 'MOZ_PLUGIN_PATH': '/usr/lib/mozilla/plugins', 'PATH': '/home/john/projects/enthought/sat-solver/.tox/py27/bin:/home/john/projects/enthought/sat-solver/.devenv-sat34/bin:/usr/local/opt/python/bin:/home/john/Library/Python/2.7/bin:/opt/packer:/home/john/projects/scripts:/home/john/.local/bin:/home/john/.local/share/node_modules/.bin:/home/john/.cabal/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl', 'ETS_TOOLKIT': 'qt4', 'MAIL': '/var/mail/john', 'LC_MESSAGES': 'en_US.UTF-8', 'HG': '/usr/bin/hg', 'LC_IDENTIFICATION': 'en_US.UTF-8', 'LD': 'ld.gold', 'LC_COLLATE': 'C', 'PWD': '/home/john/projects/enthought/sat-solver', 'JAVA_HOME': '/usr/lib/jvm/default', 'EDITOR': 'vim', 'LANG': 'en_US.UTF-8', 'PYTHONSTARTUP': '/home/john/.pythonrc', 'LC_MEASUREMENT': 'en_US.UTF-8', 'TMUX_PANE': '%3', 'PS1': '(.devenv-sat34)\\n\\[\\033[32m\\]\\a\\u@\\h \\[\\033[33m\\]\\w\\[\\033[37m\\]$(__git_ps1)\\[\\033[0m\\]\\n$ ', 'GIT_PS1_SHOWUNTRACKEDFILES': '1', 'HISTIGNORE': '&:[ ]*:exit', 'SSH_ASKPASS': '/usr/lib/ssh/x11-ssh-askpass', 'HISTCONTROL': 'ignoredups', 'GPG_TTY': 'not a tty', 'LESSCHARSET': 'utf-8', 'HOME': '/home/john', 'COLORFGBG': 'default;0', 'XDG_SEAT': 'seat0', 'SHLVL': '2', 'PLINK_PROTOCOL': 'ssh', 'LS_OPTIONS': '-F -b -T 0 --color=auto', 'GIT_PS1_SHOWSTASHSTATE': '1', 'LOGNAME': 'john', 'LESS': '-FRXM', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-jKQU1F7jyx,guid=1e92c65a576a716997cd893056538ce7', 'LC_CTYPE': 'en_US.UTF-8', 'EMAIL': 'johntyree@gmail.com', 'XDG_RUNTIME_DIR': '/run/user/1000', 'DISPLAY': ':0.0', 'LC_TIME': 'en_US.UTF-8', 'HISTFILE': '/home/john/long_history', 'LC_NAME': 'en_US.UTF-8', 'COLORTERM': 'rxvt', 'XAUTHORITY': '/home/john/.Xauthority', '_': '/home/john/projects/enthought/sat-solver/.devenv-sat34/bin/tox', 'PYTHONHASHSEED': '2053596452'}
You are using pip version 6.1.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting PyYAML (from -r requirements.txt (line 1))
  Using cached PyYAML-3.11.tar.gz
Collecting enstaller from git+https://github.com/enthought/enstaller@5a2c9be9b4a3e89b0c0f462289a0ccda1cc9b3a9#egg=enstaller (from -r requirements.txt (line 2))
  Cloning https://github.com/enthought/enstaller (to 5a2c9be9b4a3e89b0c0f462289a0ccda1cc9b3a9) to /tmp/pip-build-H7VRBj/enstaller
  Could not find a tag or branch '5a2c9be9b4a3e89b0c0f462289a0ccda1cc9b3a9', assuming commit.
    Complete output from command python setup.py egg_info:
    error in enstaller setup command: Invalid environment marker: python_version<"3.0"
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-H7VRBj/enstaller

ERROR: could not install deps [-rdev_requirements.txt]; v = InvocationError('/home/john/projects/enthought/sat-solver/.tox/py27/bin/pip install -rdev_requirements.txt (see /home/john/projects/enthought/sat-solver/.tox/py27/log/py27-1.log)', 1)
```

If I update to `tox-2.2.1`, with `pip install -U tox` everything works again.

**Comment by johntyree** [comment]
Oh I see. Travis doesn't even use tox. In that case, yes. I think this breaks `tox`.

**Comment by cournape** [comment]
You need a recent version of setuptools (it works in travis because I do `pip install -U setuptools`).

**Comment by johntyree** [comment]
The test failure here is my fault and is fixed by #72.

**Comment by johntyree** [comment]
Tada :tada: !

**Comment by johntyree** [comment]
LGTM!

**Pull request merged**
