### PR TITLE
REPO: build docs on travis

### PR DESCRIPTION
**Pull request by johntyree**
RTD doesn't seem to tell anyone if it fails.

### CODE REVIEW

**Comment by johntyree** [comment]
:dancer: @cournape

**Comment by cournape** [comment]
Can we have this as a separate job instead of building docs for every job ?

**Comment by johntyree** [comment]
We could, but why should we? I would think "everything works on every platform" is a reasonable default to want to have and building the docs adds about four seconds to the build time.

At any rate, it isn't possible to have doc-updating PRs only run the doc job anyway, right? So everything gets run no matter what you do.

**Comment by cournape** [comment]
Is it really only 4 seconds including the time to install sphinx and co ? If so, then I agree is it not worth it yet.

The main point of having a separate job is that it can run in // and not serially.

**Comment by johntyree** [comment]
It looks like it adds about 10% to the build time, but there's so much variability depending on Travis itself that it's hard to tell. Right now builds take anywhere from 1min to 3min, with or without this.

**Comment by cournape** [comment]
Just to make it clear: it is indeed not worth arguing about if it adds a few sec :)

:+1:

**Pull request merged**
