### PR TITLE
Show detailed diff in failed Scenario test output

### PR DESCRIPTION
**Pull request by johntyree**
It was getting very tedious to iterate on failed tests.

Now it is less so.

### CODE REVIEW

**Comment by cournape** [comment]
For this kind of change, it is useful to copy/paste an example before/after

**Comment by johntyree** [comment]
The original just showed a single pair of mismatched packages, based on ordering.
Now, in addition to showing the particular package that caused the error, we show all other packages which have mismatched operations, ignoring ordering.

### Before
```
1) FAIL: test_multiple_jobs (simplesat.tests.test_scenarios_policy.TestInstallSet)

   Traceback (most recent call last):
    simplesat/tests/test_scenarios_policy.py line 149 in test_multiple_jobs
      self._check_solution("multiple_jobs.yaml")
    simplesat/tests/test_scenarios_policy.py line 73 in _check_solution
      scenario.operations)
    simplesat/tests/test_scenarios_policy.py line 87 in assertEqualOperations
      self.fail(msg)
   AssertionError: Item 2: 'scipy 0.14.1rc1-1' vs 'libpng 1.6.12-1'
```

### After
```
1) FAIL: test_multiple_jobs (simplesat.tests.test_scenarios_policy.TestInstallSet)

   Traceback (most recent call last):
    simplesat/tests/test_scenarios_policy.py line 168 in test_multiple_jobs
      self._check_solution("multiple_jobs.yaml")
    simplesat/tests/test_scenarios_policy.py line 88 in _check_solution
      scenario.operations)
    simplesat/tests/test_scenarios_policy.py line 106 in assertEqualOperations
      self.fail(msg)
   AssertionError: Item 2: 'scipy 0.14.1rc1-1' vs 'libpng 1.6.12-1'
   MKL
     SOLVER  : None
     SCENARIO: UpdateOperation(package=MKL 10.2-1, source=MKL 10.3-1)
   
   libpng
     SOLVER  : InstallOperation(package=libpng 1.6.12-2)
     SCENARIO: InstallOperation(package=libpng 1.6.12-1)
   
   scipy
     SOLVER  : InstallOperation(package=scipy 0.14.1rc1-1)
     SCENARIO: RemoveOperation(package=scipy 0.14.1rc1-1)
```

**Comment by cournape** [comment]
I wonder if we leverage the pretty diff thing used for list/dict/etc... comparison ? I forgot how it worked exactly, if you don't think it is very useful, that's fine.

LGTM

**Comment by johntyree** [comment]
The problem was that the output is just too verbose to read clearly unless you manage it yourself, otherwise I'd have just used `pprint`.

**Pull request merged**
