### PR TITLE
BUG: _find_updates should allow lower version to handle downgrades.

### PR DESCRIPTION
**Pull request by cournape**
The `_find_updates` was only considering versions higher than the given package, which prevents `_find_updates` to work with downgrades.

@johntyree @jvkersch

### CODE REVIEW

**Comment by johntyree** [comment]
I haven't ventured far outside of `simplesat/sat/`, but this looks like it's probably right :)

Can you point to yaml file I can run to demonstrate the bug?

**Comment by cournape** [comment]
I don't think we have any scenario testing this, but I can add a quick unittest for transaction calculation

**Comment by johntyree** [comment]
`simplesat/tests/numpy_downgrade.yaml` requires this patch to be handled correctly.

**Comment by johntyree** [comment]
Interesting. Looks like Github orders commits by `author date` rather than `commit date`. In `git log`, these commits are ordered `a8ac, 213f, 7050`. I'd call that a bug.

**Comment by johntyree** [comment]
Ah of course!! :bulb:

This is failing because #54 is overzealous. We're pruning away packages that aren't dependencies. 

Instead, we need to make sure we don't prune other versions of relevant packages, otherwise we can never upgrade anything because we can't uninstall the current version.

**Comment by johntyree** [comment]
I've confirmed manually that #60 resolves this, so merging that, then merging master here should be good to go.

**Comment by johntyree** [comment]
#60 was merged so this is ready to go.

**Pull request merged**
