### PR TITLE
MAINT: add enum34 to the normal requirements file

### PR DESCRIPTION
**Pull request by johntyree**
@noraderam

### CODE REVIEW

**Comment by noraderam** [comment]
:+1:

**Comment by cournape** [comment]
Can we add the missing runtime requirements to `setup.py` ?

**Comment by johntyree** [comment]
What's the relationship between `requirements.txt` and `setup.py`? Should `requirements.txt` even exist?

**Comment by cournape** [comment]
Good question. The starting point is https://caremad.io/2013/07/setup-vs-requirement/

Now, there are exceptions to that rule, in particular, when you depend on dependencies not published on pypi (e.g. not OSS, or git commit), in which case requirements.txt are required. I think that used to apply, but does not anymore to satsolver (when we depended on enstaller master).

**Pull request merged**
