### PR TITLE
ENH: return error message when running checks for satisfiability 

### PR DESCRIPTION
**Pull request by prashantmital**

### CODE REVIEW

**Comment by prashantmital** [comment]
While this approach is simple enough, the need to index into the returned value to get a `True`/`False` result is less than ideal IMO. Instead we could have a class equipped with the `__bool__` (`__nonzero__` for Python < 2) method that stores the error message as one of its members. What do you think?

**Comment by noraderam** [comment]
How about we split the difference and use a named tuple?

**Comment by noraderam** [comment]
I'm confused about the test grouping: What is tested in `test_solver` and what is tested in `test_dependency_solver`?

**Comment by prashantmital** [comment]
I'll need to take a closer look to figure that out. I just *fixed* the pre-existing tests without paying too much attention to the organization.

**Comment by noraderam** [comment]
It looks like `test_dependency_solver` was added in #219, likely because it wasn't clear that tests already existed in `test_solver`

**Comment by noraderam** [comment]
I'm happy with how this looks, assuming that tests pass

**Comment by prashantmital** [comment]
@noraderam Safe to merge?

**Comment by cournape** [comment]
Can we rename `Result.result` to `Result.is_satisfiable` or something similar ?

**Comment by noraderam** [comment]
LGTM

**Pull request merged**
